KerbalStore/Controllers/StorePageController.cs
using KerbalStore.Data;
using KerbalStore.Models;
using KerbalStore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace KerbalStore.Controllers
{
    public class StorePageController : Controller
    {
        private readonly ITicketService ticketService;
        private readonly IKerbalStoreRepository kerbalStoreRepository;

        public StorePageController(ITicketService ticketService, IKerbalStoreRepository kerbalStoreRepository)
        {
            this.ticketService = ticketService;
            this.kerbalStoreRepository = kerbalStoreRepository;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("AboutUs")]
        public IActionResult AboutUs()
        {
            ViewBag.Title = "About the store";
            return View();
        }

        [HttpGet("TestErrorPage")]
        public IActionResult TestErrorPageUsingRazorPage()
        {
            throw new InvalidOperationException("Oops!");
        }

        [HttpGet]
        public IActionResult RequestPart()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RequestPart(RequestPartModel model)
        {
            if (ModelState.IsValid)
            {
                ticketService.SendTicket(model.Name, model.RocketPart);
                ViewBag.UserFeedback = "Request received, please wait for it to be reviewed by KSP staff";
                ModelState.Clear();
            }

            return View();
        }

        public IActionResult Shop()
        {
            //var results = kerbalStoreRepository.RocketParts.OrderBy(rp => rp.PartName).ToList();
            //var linqResults = from rp in kerbalStoreRepository.RocketParts
            //                  orderby rp.PartName ascending
            //                  select rp;
            var fromRepository = kerbalStoreRepository.GetAllRocketParts();

            return View(fromRepository);
        }
    }
}

KerbalStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Kerbal Store: @ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    @RenderSection("styles", false)

</head>
<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-desktop">&nbsp;</i>Welcome to the Kerbal Store!</div>
                <button class="navbar-toggle navbar-collapse" data-toggle="collapse" data-target="#menu">&#9776;</button>
            </div>
            <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="StorePage" asp-action="Index">Home</a></li>
                    <li><a asp-controller="StorePage" asp-action="Shop"><i class="fa fa-ship"></i> Browse Shop</a></li>
                    <li><a asp-controller="StorePage" asp-action="RequestPart"><i class="fa fa-recycle"></i> Request Part</a></li>
                    <li><a asp-controller="StorePage" asp-action="AboutUs">About Us</a></li>
                    <li><a asp-controller="StorePage" asp-action="TestErrorPageUsingRazorPage">Pretty Error Page</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </header>
    </div>
    <section class="container">
        <div class="text-center">
            <h2>@ViewBag.Title</h2>
        </div>
        @RenderBody()
    </section>
    <footer class="container col-md-6 col-md-offset-3">
        <br />
        <div class="text-center">Subject matter based on the game Kerbal Space Program, a space rocket construction and flight simulator that, in my opinion, has a rather cult-style following and is great fun to play! Though, most of the time you end up crashing into the planet or breaking on re-entry...</div>
    </footer>

    <script src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>